apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: metric-collector-period
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: ClusterMetricCollector
      policies:
        - type: period
          value:
            - "5"
  policyStatus: Enabled
