apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
       type: Utilization
       averageUtilization: 70
  - type: Object
    object:
      metric:
        name: NetworkTxUsage
      describedObject:
        apiVersion: v1
        kind: Pod
        name: php-apache
      target:
        type: Value
        value: 50
