apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dns-test
  namespace: openmcp
  labels:
    kubefed.io/managed: "true"
spec:
  rules:
  - host: loadalancing.openmcp.org
    http:
      paths:
      - backend:
          serviceName: iot-gateway-svc
          servicePort: 80
