apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: keti-preprocessor
#  namespace: dt
spec:
  #serviceName: "keti-preprocessor"
  replicas: 3
  labels:
    component: keti-preprocessor
  template:
    spec:
      template:
        spec:
          containers:
          - name: keti-preprocessor
    #        image: ramhiser/spark:2.0.1
            image: openmcp/keti-preprocessor:v0.0.1
            imagePullPolicy: Always
            #command: ["/bin/sh"]
            #args: ["-c", "while true; do echo hello; sleep 10;done"]
            #command: ["./start.sh"]
            command: ["./start_spark.sh"]
            #command: ["ls"]
            ports:
            - containerPort: 7077
            - containerPort: 8080
            env:
            - name: HADOOP_CONF_DIR
              value: /etc/config/hadoop-conf
            - name: QUEUE_NAME
              value: "data"
            - name: QUEUE_TOPIC
              value: "data"
            - name: ZKQUORUM
              value: "zk-cs.default.openmcp-dt-domain.svc.openmcp.dt.org:2181"
            - name: RABITMQ
              value: "mu-rabbit-rabbitmq.default.openmcp-dt-domain.svc.openmcp.dt.org"
            - name: SPARK_PERIOD_SEC
              value: "3"
            - name: INFLUXDB_SERVICE
              value: "influxdb.default.openmcp-dt-domain.svc.openmcp.dt.org"
            #volumeMounts:
            #- name: hadoop-conf
            #  mountPath: /etc/config/hadoop-conf
          #volumes:
          #- name: hadoop-conf
          #  configMap:
          #    name: hadoop-config
          imagePullSecrets:
          - name: regcred
