apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/test
    server: "10.0.3.12"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/test
    server: "10.0.3.12"
    readOnly: false
