apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: scheduler-openmcpdeployment
  namespace: openmcp
spec:
  replicas: 3
  affinity: 
    region: 
      - asia
    zone: 
      - korea
      - china
  labels:
    app: openmcp-nginx
    test: "yes"
  template:       
    spec:
      template:  
        spec:
          containers:
          - image: nginx
            name: nginx
            ports:
            - containerPort: 2020
            volumeMounts:
              - mountPath: /data
                name: shared-storage
            resources:
              requests:        
                memory: 1Gi
                cpu: 1.5 
                ephemeral-storage: 1Gi
              needs:
                gpu: true
                hba: false
          - image: ubuntu:16.04
            name: ubuntu-container
            command: ["tail", "-f", "/dev/null"]
            volumeMounts:
              - mountPath: /data
                name: 
            resources:
              requests:
                cpu: 1
                memory: 1Ki
                ephemeral-storage: 1Ki
          volumes:
            - name: shared-storage
              emptyDir: {}
          nodeSelector:
            scheduler-test: "yes"
