apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: scheduler-openmcpdeployment
  namespace: openmcp
spec:
  replicas: 3
  template:       
    spec:
      template:  
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:        
                memory: 1Gi
                cpu: 1.5 
                ephemeral-storage: 1Gi
