apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: scheduler-openmcpdeployment
  namespace: openmcp
spec:
  replicas: 3
  affinity: 
    region: 
      - asia
    zone: 
      - korea
      - china
  labels:
    app: openmcp-nginx
    test: "yes"
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            volumeMounts:
              - mountPath: /data/shared
                name: hostPathTest
            resources:
              requests:        
                memory: 1Gi
                cpu: 1.5 
                ephemeral-storage: 1Gi
              needs:
                gpu: true
                hba: false
          volumes:
            - name: hostPathTest
              hostPath:
                path: /tmp 
                type: Directory