apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment3
  namespace: openmcp
spec:
  replicas: 3
  affinity: 
    region: 
      - AS
    zone: 
      - KR
      - CH
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            ports:
            - containerPort: 1234
            resources:
              requests:
                memory: "100Mi"
                cpu: "1"
          - image: nginx
            name: server
            ports:
            - containerPort: 5678
          nodeSelector:
            openmcp-scheduler: "yes"
