apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicyEngine
metadata:
  name: analytic-metrics-weight
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPAnalyticEngine
      policies:
        - type: CPU
          value:
            - "0.4"
        - type: Memory
          value:
            - "0.4"
        - type: FS
          value:
            - "0.2"
  rangeOfApplication: All
  policyStatus: Enabled
