apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment3
  namespace: openmcp
spec:
  replicas: 3
  labels:
    app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:        
                memory: 1Gi
                cpu: 1.5 
                ephemeral-storage: 1Gi
              needs:
                gpu: true
                hba: true
                raid: false
          - image: k8s.gcr.io/pause:2.0
            name: pause
            resources:
              requests:
                cpu: 1
                memory: 1Ki
                ephemeral-storage: 1Ki
              needs:
                gpu: true
                hba: false
                raid: true