apiVersion: v1
kind: Service
metadata:
  name: cluster-resource-collector
  namespace: rescollect
  labels:
    name: openmcp-resource-collector
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    name: openmcp-resource-collector
