apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: has-iot-data-collector
spec:
  hpaTemplate:
    spec:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: iot-data-collector
      minReplicas: 1
      maxReplicas: 15
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80
        - type: Object
          object:
            metric:
              name: FsUsage
            describedObject:
              apiVersion: v1
              kind: Pod
              name: iot-data-collector
            target:
              type: Value
              value: 60000
        - type: Object
          object:
            metric:
              name: NetworkTxUsage
            describedObject:
              apiVersion: v1
              kind: Pod
              name: iot-data-collector
            target:
              type: Value
              value: 60000
  vpaMode: Auto
