apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: analytic-metrics-weight
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPAnalyticEngine
      policies:
        - type: CPU
          value:
            - "0.5"
        - type: Memory
          value:
            - "2.0"
        - type: FS
          value:
            - "0.2"
        - type: GeoRate
          value:
            - "0.8"
  policyStatus: Enabled
