apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalregistries.openmcp.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: openmcp.k8s.io
  names:
    kind: GlobalRegistry
    listKind: GlobalRegistryList
    plural: globalregistries
    singular: globalregistry
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GlobalRegistry is the Schema for the globalregistries API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GlobalRegistrySpec defines the desired state of GlobalRegistry
            properties:
              command:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
              imageName:
                description: Command 가 delete 인 경우에만 포함.
                type: string
              tagName:
                type: string
            required:
            - command
            type: object
          status:
            description: GlobalRegistryStatus defines the observed state of GlobalRegistry
            properties:
              Reason:
                description: Reason indicates the reason for any backup related failures.
                type: string
              lastSuccessDate:
                description: LastSuccessDate indicate the time to get snapshot last
                  time
                format: date-time
                type: string
              succeeded:
                description: Succeeded indicates if the backup has Succeeded.
                type: boolean
            required:
            - succeeded
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
