apiVersion: keti.example.com/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: openmcphpa-request
  namespace: openmcp
spec:
  hpaTemplate:
    spec:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: openmcp-pod-request
      minReplicas: 1
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 50
        - type: Resource
          resource:
            name: memory
            targetAverageUtilization: 50
  vpaMode: Never
