apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: openmcp-nginx-deploy
  namespace: openmcp
spec:
  replicas: 9
  labels:
      app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "100Mi"
                cpu: "1"
