apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment
  namespace: openmcp
spec:
  replicas: 8
  labels:
      app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "1Gi"
                cpu: "1"
