apiVersion: keti.example.com/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: openmcphpa-request
  namespace: openmcp
spec:
  hpaTemplate:
    spec:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: openmcp-pod-request
      minReplicas: 3
      maxReplicas: 16
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 50
  vpaMode: Never
