apiVersion: keti.example.com/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: openmcphpa-request
  namespace: test
spec:
  hpaTemplate:
    spec:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: openmcp-pod-request
      minReplicas: 2
      maxReplicas: 14
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Object
          object:
            metric:
              name: test-metrics
            describedObject:
              apiVersion: v1
              kind: Pod
              name: openmcp-pod-test
            target:
              type: Value
              value: 100
  vpaMode: Never
