apiVersion: v1
kind: PersistentVolume
metadata:
  name: 3gi-a04
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/3Gi/a04
    server: "10.0.3.12"
    readOnly: false
