apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-metric-collector
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-metric-collector
  template:
    metadata:
      labels:
        name: openmcp-metric-collector
    spec:
      serviceAccountName: openmcp-metric-collector
      containers:
        - name: openmcp-metric-collector
          # Replace this with the built image name
          image: openmcp/openmcp-metric-collector:v0.0.1
          command:
          - openmcp-metric-collector
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFLUX_IP
              value: "10.0.3.20"
            - name: INFLUX_PORT
              value: "31051"
            - name: INFLUX_USERNAME
              value: "root"
            - name: INFLUX_PASSWORD
              value: "root"
            - name: OPERATOR_NAME
              value: "openmcp-metric-collector"


