apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment-affinity
  namespace: openmcp
spec:
  replicas: 3
  affinity: 
    region: 
      - AS
    zone: 
      - KR
      - CH
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "100"
                cpu: "0.5"
