apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment-defineport
  namespace: openmcp
spec:
  replicas: 5
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "100"
                cpu: "1"
