apiVersion: v1
kind: Service
metadata:
  name: iot-gateway-svc
  namespace: openmcp
  labels:
    component: iot-gateway-svc
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30802
    name: http
  - port: 5683
    nodePort: 30402
    name: coap
    protocol: UDP
  - port: 1883
    nodePort: 30487
    name: mqtt
  #clusterIP: 10.96.0.255
  selector:
    app: iot-gateway
    component: iot-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-data-collector
spec:
  selector:
    matchLabels:
      app: iot-data-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-data-collector
        component: iot-data-collector
    spec:
      #securityContext:
        #runAsUser: 1001
        #fsGroup: 1001
      containers:
      - name: iot-gateway
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        image: openmcp/keti-iotgateway:v1.0
        resources:
          requests:
            memory: 256M
            cpu: 125m
          limits:
            memory: 256M
            cpu: 125m
        ports:
        - containerPort: 8888
          name: http
        - containerPort: 5683
          name: coap
        - containerPort: 1883
          name: mqtt
        env:
        - name: IOT_SERVICE_CONNECT
          #value: "iot-gateway-svc.default.svc.cluster.local"
          #value: "10.96.0.255"
          value: "0.0.0.0"
        - name:  MQTT_TIMEOUT
          value: "60"
        - name:  SERVER_kafka_connect
          value: "kafka-svc.default.svc.cluster.local"
        securityContext:
         capabilities:
           add:
             - NET_ADMIN
      imagePullSecrets:
      - name: regcred

