apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment4
  namespace: openmcp
spec:
  replicas: 1
  affinity: 
    region: 
      - AS
    zone: 
      - KR
      - CH
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "100Mi"
                cpu: "1"
