apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/influxdb
    server: "10.0.3.12"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/influxdb
    server: "10.0.3.12"
    readOnly: false
