apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: openmcp-deployment
  namespace: openmcp
spec:
  replicas: 4
  labels:
      app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
