apiVersion: v1
kind: Service
metadata:
  name: openmcp-analytic-engine
  namespace: openmcp
  labels:
    name: openmcp-analytic-engine
spec:
  type: LoadBalancer
  ports:
  - port: 2061
    targetPort: 2061
    nodePort: 32061
    protocol: TCP
  selector:
    name: openmcp-analytic-engine
