apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-custom-test
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-custom-test
  template:
    metadata:
      labels:
        name: openmcp-custom-test
    spec:
      serviceAccountName: openmcp-custom-test
      containers:
        - name: custom-test
          # Replace this with the built image name
          image: atyx300/openmcp-custom-test:v0.0.1
          command:
          - openmcp-custom-test
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openmcp-custom-test"
