apiVersion:  keti.example.com/v1alpha1
kind: OpenMCPIngress
metadata:
  name: openmcp-ingress
  namespace: openmcp
spec:
  template:
    spec:
      rules:
      - host: openmcp.service.org
        http:
          paths:
          - backend:
              serviceName: openmcp-service
              servicePort: 80


