apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicyEngine
metadata:
  name: log-version
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: All-OpenMCP-Resource-Controller
      policies:
        - type: Version
          value:
            - "1"
  policyStatus: Enabled
