apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicyEngine
metadata:
  name: hpa-minmax-distribution-mode
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPHybridAutoScaler
      policies:
        - type: Mode
          value:
            - Unequal
  rangeOfApplication: All
  policyStatus: Enabled
