apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-controller
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sync-controller
  template:
    metadata:
      labels:
        name: sync-controller
    spec:
      serviceAccountName: sync-controller
      containers:
        - name: sync-controller
          # Replace this with the built image name
          image: atyx300/sync-controller:v0.0.1
          command:
          - sync-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sync-controller"
