apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-migration
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-migration
  template:
    metadata:
      labels:
        name: openmcp-migration
    spec:
      serviceAccountName: openmcp-migration-sa
      containers:
        - name: openmcp-migration
          # Replace this with the built image name
          image: leelee3150/openmcp-migration:v0.0.3
          command:
          - openmcp-migration
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openmcp-migration"