apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: http-generator
  labels:
    app: http-generator
    component: http-generator
spec:
  replicas: 1
  template:
    selector:
      matchLabels:
        app: http-generator
        component: http-generator
    template:
      metadata:
        labels:
          app: http-generator
          component: http-generator
      spec:
        #securityContext:
          #runAsUser: 1001
          #fsGroup: 1001
        containers:
        - name: http-generator
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          image: openmcp/keti-http-generator:v1.1
          command: ["/app/start_http.sh"]
          resources:
            requests:
              memory: 256M
              cpu: 125m
            limits:
              memory: 256M
              cpu: 125m
          env:
          - name: COMPANY_NAME
            value: "SHINHAN"
          - name: CRANE_NAME
            value: "Crane_1"
          - name: IOT_GATEWAY_IP
            value: "iot-gateway-svc.default.svc.cluster.local"
          - name: HTTP_PORT
            value: "8888"
          - name: GEN_PERIOD_SEC
            value: "3"
        imagePullSecrets:
        - name: regcred
